### ISSUE TITLE
Checkpoint #3 ready for review

### ISSUE THREAD

**Issue by jcmann** [jcmann/dmbook#13]
Hi @pawaitemadisoncollege ! This completely and totally slipped my brain because I had some parts "done" in advance... oops!

Technically a comparatively (to now) smaller version is still deployed here: http://dmbook-env.eba-w8kmg5pp.us-east-2.elasticbeanstalk.com/ 

It is showing db data, but I've just added a couple more like that for testing purposes since that deployment. 

I do have authentication implemented in my frontend like we've talked about -- still using that slightly hacky manual refresh! However, my original plan to deploy that to GitHub pages has been complicated (I think) by the fact that my .gitignore ignores AWS Amplify config-related files that have secrets in them. Is it okay if for the sake of this project I only properly deploy the backend, and the frontend just has to be cloned down and started with the instructions in its [readme](https://github.com/jcmann/dmbook-frontend/blob/main/README.md)? I feel like finding a way to securely deploy the frontend (maybe it just ends up on an ec2 instance honestly) could be a good new tech-debt-type stretch goal...

**Comment by pawaitemadisoncollege** [comment]
Hi Jen! 

I think the root issue might be related to .gitignoring the build directory of the amplify app. Here are the high level steps we use in the Adv Cloud class to deploy a react/amplify app to GithubPages:

1. Update package.json with what your home page will be on GitHub Pages. Something like: "homepage": "https://pwaitemadisoncollege.github.io/amplify-react-app".
2. Run npm run build.
3. Rename `build` to `docs`. (because the build directory is ignored )
4. Commit and push.
5. In GitHub settings for your repository, specify the branch and folder to set for GitHub Pages.

Let me know if that helps, or if you have any questions. 

BTW  - it is just this coming week that we are doing a more complete cognito app in the adv cloud class (the chapter 4 app in the textbook). I'll share the source with you in case it helps!

**Comment by jcmann** [comment]
Woo! That `/build` directory was the problem! I actually just removed that from the gitignore and that seems to have fixed it! It's alive here now :) https://jcmann.github.io/dmbook-frontend/

(@pawaitemadisoncollege Thanks so much!! )

**Comment by pawaitemadisoncollege** [comment]
Woohoo! Nice job Jen!

On Nov 18, 2021, at 8:41 PM, jcmann ***@***.******@***.***>> wrote:



Woo! That /build directory was the problem! I actually just removed that from the gitignore and that seems to have fixed it! It's alive here now :) https://jcmann.github.io/dmbook-frontend/<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fjcmann.github.io%2Fdmbook-frontend%2F&data=04%7C01%7Cpawaite%40madisoncollege.edu%7C8079eebb2bd943cebec508d9ab060ad7%7C33f001466fcc49e9b5687896b3069d44%7C0%7C0%7C637728864718722952%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BjiiwpLsRcVuZKljbH4wKB3lDJCqGqveJsVfTuP7u%2Bc%3D&reserved=0>

***@***.***<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpawaitemadisoncollege&data=04%7C01%7Cpawaite%40madisoncollege.edu%7C8079eebb2bd943cebec508d9ab060ad7%7C33f001466fcc49e9b5687896b3069d44%7C0%7C0%7C637728864718732907%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lAShvayuPz9akSm%2BfAlIEXdn2TB%2BldChOMnJ5HX%2F3pw%3D&reserved=0> Thanks so much!! )

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjcmann%2Fdmbook%2Fissues%2F13%23issuecomment-973675216&data=04%7C01%7Cpawaite%40madisoncollege.edu%7C8079eebb2bd943cebec508d9ab060ad7%7C33f001466fcc49e9b5687896b3069d44%7C0%7C0%7C637728864718732907%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tzLgBsg4CwuiLOQ8LHXfGcAJMA6M2K96cNYUw4q4JMY%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADJ3KIQCXTL7JC3Z64O37FTUMW2MJANCNFSM5H5XL2BA&data=04%7C01%7Cpawaite%40madisoncollege.edu%7C8079eebb2bd943cebec508d9ab060ad7%7C33f001466fcc49e9b5687896b3069d44%7C0%7C0%7C637728864718742864%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FxjMa8eIcanGaP3r2CAsvBSyYUtdzwW92UTkdYmCNB4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpawaite%40madisoncollege.edu%7C8079eebb2bd943cebec508d9ab060ad7%7C33f001466fcc49e9b5687896b3069d44%7C0%7C0%7C637728864718742864%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7Wxz0uYm92n6YWck9SdO7fGv0iEr1zGjjsjuBtMhbWY%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpawaite%40madisoncollege.edu%7C8079eebb2bd943cebec508d9ab060ad7%7C33f001466fcc49e9b5687896b3069d44%7C0%7C0%7C637728864718752825%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fI0FOG6R%2BaxXtCNkdLrU781Ho0DNwFxLgIS7pD8QSOI%3D&reserved=0>.
