### ISSUE TITLE
Exercise 5 ready for review

### ISSUE THREAD

**Issue by jcmann** [jcmann/dmbook#3]
Hi @pawaitemadisoncollege ! Exercise 5 is ready for review. I got the search by properties working, and I'm going to try and generalize it at some point I think. I think that's a reasonable goal for the finished project! 

My key learning point this week was definitely figuring out the where clause. I honestly am not a fan of the Hibernate documentation because it doesn't just come out and say what everything is or needs to be, so it was hard to figure out exactly what part of what ends up being the where clause needed to correspond to what part of the POJO. But, I at least got it working!

I had to troubleshoot some environment stuff that took me a couple hours today. I think it might've been an issue with my database in the end -- I hadn't actually specified the cascade in the SQL, but I did have it in the bean, but there were also some inconsistencies in my environments across the two computers' VM installs that I use to work on this class. 

A slew of links I used: 
- https://docs.jboss.org/hibernate/orm/5.4/quickstart/html_single/#hibernate-gsg-tutorial-basic-test 
- https://stackoverflow.com/questions/47334306/in-hibernate-5-whats-the-criteriaquery-equivalent-of-criterias-restriction-an
- https://stackoverflow.com/questions/4401240/hibernate-criteria-vs-hql-which-is-faster
- https://www.baeldung.com/hibernate-criteria-queries
- https://stackoverflow.com/questions/43493889/cannot-delete-or-update-a-parent-row-a-foreign-key-constraint-fails-mysql/43494234
- https://stackoverflow.com/questions/930900/how-do-i-set-the-time-zone-of-mysql
- https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html
- https://stackoverflow.com/questions/19903610/how-to-set-permanent-default-timezone-in-mysql-server/19904846

**Comment by pawaitemadisoncollege** [comment]
@jcmann GREAT work! 

Regarding generalizing the dao - yes!!! Check out the abstract/generic dao in the week 5 follow-up videos and plan to use it in your project so that you can use a single dao! You will still have unit tests each for each entity(dao) to verify annotations and database relationships are set up correctly.

This is well done (many students miss this case): https://github.com/jcmann/dmbook/blob/8be53beb286f8a4cdcf08d787d6fcf02d80906eb/src/test/java/com/jenmann/persistence/UserDaoTest.java#L94-L102.  

- [ ] It would be a good idea to include a test to verify that when character is deleted that the user is not deleted - not so much to make sure that it works now, but to ensure future work doesn't break this.
- [ ] .equals for full entity comparison versus: https://github.com/jcmann/dmbook/blob/8be53beb286f8a4cdcf08d787d6fcf02d80906eb/src/test/java/com/jenmann/persistence/CharactersDaoTest.java#L68
